// Open-Decision Monitoring V1 — the review horizon the investor chooses
// when recording a decision (docs/data-model.md §5 Decision.review_by_date).
// The choice is EXPLICIT: a date, or a deliberate "no review date". A
// missing choice is a validation error, never silently "no horizon"; the
// date is never generated by the app or inferred from AI output. Date-only,
// stored at 00:00Z like transaction dates, so "due on the review date"
// compares on the calendar day.
import { z } from "zod";

export const reviewHorizonChoiceSchema = z.discriminatedUnion("choice", [
  // .strict(): a payload that says "none" but also carries a date (or vice
  // versa) is contradictory and is refused, never silently reconciled.
  z.object({ choice: z.literal("date"), reviewByDate: z.coerce.date() }).strict(),
  z.object({ choice: z.literal("none") }).strict(),
]);
export type ReviewHorizonChoice = z.infer<typeof reviewHorizonChoiceSchema>;

export class ReviewHorizonError extends Error {}

/** Date-only at 00:00Z. */
export function normalizeReviewByDate(d: Date): Date {
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
}

/**
 * Resolves the investor's explicit choice into the value to persist.
 * A date before the decision's own day is refused (it could never be
 * anything but immediately "due" for a reason the investor did not state).
 */
export function resolveReviewByDate(choice: ReviewHorizonChoice, decisionDate: Date): Date | null {
  if (choice.choice === "none") return null;
  if (Number.isNaN(choice.reviewByDate.getTime())) throw new ReviewHorizonError("Review date is not a valid date.");
  const reviewByDate = normalizeReviewByDate(choice.reviewByDate);
  if (reviewByDate.getTime() < normalizeReviewByDate(decisionDate).getTime()) {
    throw new ReviewHorizonError("Review date cannot be before the decision date.");
  }
  return reviewByDate;
}
