import { anthropic, CLAUDE_MODEL } from "./client";
import type { SelectedTransaction } from "@/lib/interview/select-transactions";

// Deterministic — turns already-computed facts (docs/data-model.md's "AI
// doesn't invent facts") into a plain-text brief for the model. No
// number here is generated by AI; the model only phrases a question
// about numbers it's handed.
export function describeTransactionFacts(candidate: SelectedTransaction): string {
  const { transaction, category, realizedPnlPercent, holdingPeriodDays } = candidate;
  const action = transaction.transactionType === "buy" ? "Bought" : "Sold";
  const amount =
    transaction.quantity !== null && transaction.price !== null
      ? `${transaction.quantity} shares at $${transaction.price.toFixed(2)}/share`
      : `for a total of $${Math.abs(transaction.amount).toFixed(2)}`;
  const date = transaction.transactionDate.toISOString().slice(0, 10);

  const parts = [`${action} ${transaction.ticker} on ${date}: ${amount}.`];
  if (realizedPnlPercent !== undefined) {
    const direction = realizedPnlPercent >= 0 ? "gain" : "loss";
    parts.push(`This closed with a ${Math.abs(realizedPnlPercent).toFixed(1)}% ${direction}.`);
  }
  if (holdingPeriodDays !== undefined) {
    parts.push(`Held for ${holdingPeriodDays} day(s) before selling.`);
  }
  parts.push(`(Selected for this interview because it was your: ${category.replace(/_/g, " ")}.)`);

  return parts.join(" ");
}

const SYSTEM_PROMPT = `You are conducting a brief onboarding interview for a personal investing journal app. Your job is to ask ONE specific, concrete, non-judgmental question about the reasoning behind a single real trade the investor made. You are told objective facts about the trade (already computed) — never invent numbers, never restate ones you weren't given, and never guess at facts you don't have. The goal is to learn how this person actually thinks as an investor, not to quiz or grade them. Keep the question conversational, short, and specific to this trade — not generic ("why did you buy this?" is too generic; "what made AAPL stand out to you right after that 15% drop?" is the kind of specificity to aim for, using only facts actually provided).`;

const QUESTION_TOOL = {
  name: "ask_question",
  description: "Ask the investor one specific follow-up question about this trade.",
  input_schema: {
    type: "object" as const,
    properties: {
      question: {
        type: "string" as const,
        description: "A single, specific, conversational question — no preamble, just the question.",
      },
    },
    required: ["question"],
  },
};

export async function generateInterviewQuestion(candidate: SelectedTransaction): Promise<string> {
  const facts = describeTransactionFacts(candidate);

  const response = await anthropic.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: 300,
    system: SYSTEM_PROMPT,
    tools: [QUESTION_TOOL],
    tool_choice: { type: "tool", name: "ask_question" },
    messages: [{ role: "user", content: facts }],
  });

  const toolUse = response.content.find((block) => block.type === "tool_use");
  if (!toolUse || toolUse.type !== "tool_use") {
    throw new Error("AI did not return a question via the expected tool call.");
  }

  const input = toolUse.input as { question?: unknown };
  if (typeof input.question !== "string" || input.question.trim() === "") {
    throw new Error("AI returned an empty or malformed question.");
  }

  return input.question.trim();
}
